language: python
python:
  - "2.7"
before_install:
  # Postgres 9.3 install
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.3 >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-9.3 postgresql-server-dev-9.3 postgresql-client-9.3 postgresql-contrib-9.3 postgresql-plpython-9.3
  - sudo chmod 777 /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" > /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/9.3/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  # Install the 'plxslt' extension language
  - sudo apt-get install libxml2-dev libxslt-dev
  - git clone https://github.com/petere/plxslt.git
  - cd plxslt && sudo make && sudo make install && cd ..
  # install rhaptos.cnxmlutils
  - git clone https://github.com/Connexions/rhaptos.cnxmlutils.git
  - pip install -e rhaptos.cnxmlutils --use-mirrors
  # install cnx-query-grammar
  - git clone https://github.com/Connexions/cnx-query-grammar.git
  - pip install -e cnx-query-grammar --use-mirrors
  # install cnx-archive
  - git clone https://github.com/Connexions/cnx-archive.git
  - pip install -e cnx-archive --use-mirrors
install:
  - pip install -e . --use-mirrors
before_script:
  # Set up postgres roles
  - sudo -u postgres psql -d postgres -c "CREATE USER cnxuser;"
  - sudo -u postgres psql -d postgres -c "CREATE USER cnxarchive WITH SUPERUSER PASSWORD 'cnxarchive';"
  # Set up the database
  - sudo -u postgres createdb -O cnxarchive cnxarchive-testing
script:
  - python -m unittest discover
env:
  - DB_CONNECTION_STRING="dbname=cnxarchive-testing user=cnxarchive password=cnxarchive host=localhost port=5432"
notifications:
  email: false
