language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
before_install:
  - sudo apt-get update
  # Install the 'plpython' extension language
  - sudo apt-get install postgresql-plpython-9.3
  # Install the 'plxslt' extension language
  - sudo apt-get install libxml2-dev libxslt-dev postgresql-server-dev-9.3
  - git clone https://github.com/petere/plxslt.git
  - cd plxslt && sudo make && sudo make install && cd ..
  # install rhaptos.cnxmlutils
  - git clone https://github.com/Connexions/rhaptos.cnxmlutils.git
  - cd rhaptos.cnxmlutils && sudo /usr/bin/python setup.py install && cd ..
  # install cnx-query-grammar
  - git clone https://github.com/Connexions/cnx-query-grammar.git
  - cd cnx-query-grammar && sudo /usr/bin/python setup.py install && cd ..
  # install the bug-fixes branch of plpydbapi
  - git clone -b bug-fixes https://github.com/Connexions/plpydbapi.git
  - cd plpydbapi && sudo /usr/bin/python setup.py install && cd ..
  # install cnx-archive
  - git clone https://github.com/Connexions/cnx-archive.git
  - cd cnx-archive && sudo /usr/bin/python setup.py install && cd ..
install:
  - sudo /usr/bin/python setup.py install
before_script:
  # Set up postgres roles
  - sudo -u postgres psql -d postgres -c "CREATE USER cnxuser;"
  - sudo -u postgres psql -d postgres -c "CREATE USER cnxarchive WITH SUPERUSER PASSWORD 'cnxarchive';"
  # Set up the database
  - sudo -u postgres createdb -O cnxarchive cnxarchive-testing
script:
  - sudo -E /usr/bin/python setup.py test
env:
  - DB_CONNECTION_STRING="dbname=cnxarchive-testing user=cnxarchive password=cnxarchive host=localhost port=5432"
notifications:
  email: false
